# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:
  jassoncodesapi:
    image: jassoncodesapi
    build:
      context: .
      dockerfile: src/Jasson.Codes.Api/Dockerfile
      args:
        - configuration=Debug
    ports:
      - 5000:5000
      - 5001:5001
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
