
services:
  resumeapp_api:
    image: resumeapp_api
    container_name: resumeapp_api_container
    build:
      context: .
      dockerfile: src/Jasson.Codes.Api/Dockerfile
    depends_on:
      resumeapp_db:
        condition: service_started
        restart: true
    ports:
      - "5000:5000"
      - "5001:5001"
    environment:
        - ASPNETCORE_ENVIRONMENT=Development
        - ASPNETCORE_URLS=https://+:5001;http://+:5000
        - ASPNETCORE_Kestrel__Certificates__Default__Password=JassonCodesApi
        - ASPNETCORE_Kestrel__Certificates__Default__Path=/certs/aspnetapp.pfx
    volumes:
      - resumeapp_api_vol:/certs:ro

  resumeapp_db:
    container_name: resumeapp_postgresdb_container
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ResumeAppDB
    volumes:
      - resumeapp_db_vol:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  
  resumeapp_pgadmin:
    container_name: resumeapp_pgadmin_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5452:80"
    volumes:
      - resumeapp_pgdamdmin_vol:/var/lib/pgadmin

volumes:
  resumeapp_api_vol:
    name: resumeapp_api_vol
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./certs
  resumeapp_db_vol:
    name: resumeapp_db_vol
  resumeapp_pgdamdmin_vol:
      name: resumeapp_pgdamdmin_vol